[workspace]

members = [
    "age-plugin-tlock",
    "tlock",
    "tlock_age"
]

[workspace.dependencies]
age = "0.9"
age-core = "0.9"
anyhow = "1.0"
criterion = "0.4"
drand_core = "0.0.14"
getrandom = "0.2"
hex = "0.4"
rand = { version = "0.8", default-features = false }
thiserror = "1.0.51"
